export const AVATAR_COLORS = [
  "bg-[#CFE8FC] text-[#1463B2]",
  "bg-[#FDE2E4] text-[#C03221]",
  "bg-[#E8EAF6] text-[#3949AB]",
  "bg-[#D0F4DE] text-[#2E7D32]",
  "bg-[#FFF3CD] text-[#A67C00]",
  "bg-[#E1F5FE] text-[#0277BD]",
  "bg-[#FAE0FF] text-[#78008FBF]",
  "bg-[#DDF4CC] text-[#317000BF]",
  "bg-[#EFEFEF] text-[#757575BF]",
];

export const REFERRALS = [

   { id: "DOC-101", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-102", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-103", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-104", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-105", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-106", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-107", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-108", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-109", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-110", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  
  { id: "DOC-111", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-112", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-113", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-114", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-115", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-116", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-117", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-118", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-119", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-120", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-121", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-122", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-123", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-124", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-125", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-126", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-127", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-128", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-129", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-130", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-131", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-132", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-133", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-134", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-135", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-136", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-137", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-138", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-139", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-140", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-141", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-142", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-143", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-144", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-145", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-146", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-147", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-148", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-149", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-150", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-151", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-152", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-153", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-154", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-155", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-156", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-157", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-158", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-159", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-160", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-161", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-162", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-163", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-164", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-165", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-166", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-167", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-168", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-169", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-170", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

  { id: "DOC-171", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-172", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-173", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-174", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-175", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-176", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-177", name: "MindWell Therapy", type: "Therapist", specialization: "Psychology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-178", name: "Dr. James Wilson", type: "Doctor", specialization: "Orthopedics", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-179", name: "Dr. Sarah Johnson", type: "Doctor", specialization: "Cardiology", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },
  { id: "DOC-180", name: "LifeCare Pharmacy", type: "Pharmacy", specialization: "-", phone: "+1 (55) 123-456", email: "sarah.johnson@email.com" },

];